Task/refactor my books two
ThePalaceProject/ios-core pull request #252
Opened 2023-02-16 22:26 UTC by mauricecarrier7

**What's this do?**
[Description of what this PR does goes here]

**Why are we doing this? (w/ Notion link if applicable)**
[Quick blurb about why the code is needed and Notion link goes here / Do these changes meet the business requirements of the story?]

**How should this be tested? / Do these changes have associated tests?**
[Description of any tests that need to be performed once merged goes here]

**Dependencies for merging? Releasing to production?**
[Description of any watchouts, dependencies, or issues we should be aware of goes here]

**Does this include changes that require a new Palace build for QA?**
[Bump the Palace build number to generate a new build on ThePalaceProject/ios-binaries]

**Has the application documentation been updated for these changes?**

**Did someone actually run this code to verify it works?**

2023-02-21 21:24 UTC, vladimirfedorov requested changes

2023-02-22 21:57 UTC, mauricecarrier7 commented on Palace/MyBooks/MyBooks/BookCell/BookCellModel.swift
> +  func didSelectReturn() {
Caused by navigation stack issues, resolved

2023-02-22 22:02 UTC, mauricecarrier7 commented on Palace/MyBooks/MyBooks/MyBooksViewModel.swift
> +  let facetViewModel: FacetViewModel = FacetViewModel(
Navigation issue resolved

2023-02-22 22:02 UTC, mauricecarrier7 commented on Palace/MyBooks/MyBooks/MyBooksViewModel.swift
> +  func refresh() {
updated

2023-03-06 15:53 UTC, vladimirfedorov approved these changes
Looks good to me

2023-03-06 16:10 UTC, merged